name: DungeonGenerator
version: '1.0'
main: net.rikusen.dungeongenerator.DungeonGenerator
api-version: 1.14
author: rikusen0335
commands:
  dg:
    alias: dungeongenerator
    description: DungeonGenerator command
    usage: "/dg generate | /dg help"